package top.moma.example.algo;

import com.alibaba.fastjson2.JSON;
import java.util.List;
import java.util.stream.Collectors;
import top.moma.example.algo.JsonData.DataDTO;

public class PhaseJson {
  public static void main(String[] args) {
    String dataJson =
        "{\n"
            + "  \"data\": [\n"
            + "    {\n"
            + "      \"altCode\": \"120001\",\n"
            + "      \"displayName\": \"9PSB\",\n"
            + "      \"opayCode\": \"100000\",\n"
            + "      \"shortCode\": \"940\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090270\",\n"
            + "      \"displayName\": \"AB Microfinance Bank\",\n"
            + "      \"opayCode\": \"100001\",\n"
            + "      \"shortCode\": \"090\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100028\",\n"
            + "      \"displayName\": \"AG Mortgage Bank\",\n"
            + "      \"opayCode\": \"100002\",\n"
            + "      \"shortCode\": \"60252\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090531\",\n"
            + "      \"displayName\": \"AKU Microfinance Bank\",\n"
            + "      \"opayCode\": \"100003\",\n"
            + "      \"shortCode\": \"51336\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090001\",\n"
            + "      \"displayName\": \"ASOSavings & Loan\",\n"
            + "      \"opayCode\": \"100004\",\n"
            + "      \"shortCode\": \"401\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090633\",\n"
            + "      \"displayName\": \"AWACASH MICROFINANCE BANK\",\n"
            + "      \"opayCode\": \"100005\",\n"
            + "      \"shortCode\": \"51351\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"070010\",\n"
            + "      \"displayName\": \"Abbey Mortgage Bank\",\n"
            + "      \"opayCode\": \"100006\",\n"
            + "      \"shortCode\": \"801\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000014\",\n"
            + "      \"displayName\": \"Access Bank\",\n"
            + "      \"opayCode\": \"100007\",\n"
            + "      \"shortCode\": \"044\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100013\",\n"
            + "      \"displayName\": \"Access Money\",\n"
            + "      \"opayCode\": \"100008\",\n"
            + "      \"shortCode\": \"113\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100052\",\n"
            + "      \"displayName\": \"Access Y'ello & Beta\",\n"
            + "      \"opayCode\": \"100009\",\n"
            + "      \"shortCode\": \"581\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090134\",\n"
            + "      \"displayName\": \"Accion MFB\",\n"
            + "      \"opayCode\": \"100010\",\n"
            + "      \"shortCode\": \"091\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090160\",\n"
            + "      \"displayName\": \"Addosser Microfinance Bank\",\n"
            + "      \"opayCode\": \"100011\",\n"
            + "      \"shortCode\": \"930\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090155\",\n"
            + "      \"displayName\": \"Advans La Fayette\",\n"
            + "      \"opayCode\": \"100012\",\n"
            + "      \"shortCode\": \"195\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090518\",\n"
            + "      \"displayName\": \"Afemai Microfinance Bank\",\n"
            + "      \"opayCode\": \"100013\",\n"
            + "      \"shortCode\": \"50025\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090489\",\n"
            + "      \"displayName\": \"Alvana Microfinance Bank\",\n"
            + "      \"opayCode\": \"100014\",\n"
            + "      \"shortCode\": \"50066\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090629\",\n"
            + "      \"displayName\": \"Amegy Microfinance Bank\",\n"
            + "      \"opayCode\": \"100015\",\n"
            + "      \"shortCode\": \"50925\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090645\",\n"
            + "      \"displayName\": \"Amucha Microfinance Bank\",\n"
            + "      \"opayCode\": \"100016\",\n"
            + "      \"shortCode\": \"50072\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090469\",\n"
            + "      \"displayName\": \"Aniocha Microfinance Bank\",\n"
            + "      \"opayCode\": \"100017\",\n"
            + "      \"shortCode\": \"947\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090287\",\n"
            + "      \"displayName\": \"AssetMatrix MFB\",\n"
            + "      \"opayCode\": \"100018\",\n"
            + "      \"shortCode\": \"404\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090581\",\n"
            + "      \"displayName\": \"BANC CORP MICROFINANCE BANK\",\n"
            + "      \"opayCode\": \"100019\",\n"
            + "      \"shortCode\": \"50117\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090176\",\n"
            + "      \"displayName\": \"BOSAK MFB\",\n"
            + "      \"opayCode\": \"100020\",\n"
            + "      \"shortCode\": \"50145\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090529\",\n"
            + "      \"displayName\": \"Bankly Microfinance Bank\",\n"
            + "      \"opayCode\": \"100021\",\n"
            + "      \"shortCode\": \"51341\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090136\",\n"
            + "      \"displayName\": \"Baobab Microfinance Bank\",\n"
            + "      \"opayCode\": \"100022\",\n"
            + "      \"shortCode\": \"50992\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090117\",\n"
            + "      \"displayName\": \"Boctrust Microfinance Limited\",\n"
            + "      \"opayCode\": \"100023\",\n"
            + "      \"shortCode\": \"51213\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090454\",\n"
            + "      \"displayName\": \"Borstal Microfinance Bank\",\n"
            + "      \"opayCode\": \"100024\",\n"
            + "      \"shortCode\": \"51028\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"050006\",\n"
            + "      \"displayName\": \"Branch International Financial Services\",\n"
            + "      \"opayCode\": \"100025\",\n"
            + "      \"shortCode\": \"40163\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090308\",\n"
            + "      \"displayName\": \"Brightway Microfinance Bank\",\n"
            + "      \"opayCode\": \"100026\",\n"
            + "      \"shortCode\": \"51153\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090655\",\n"
            + "      \"displayName\": \"Bunkure Microfinance Bank\",\n"
            + "      \"opayCode\": \"100027\",\n"
            + "      \"shortCode\": \"51096\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100026\",\n"
            + "      \"displayName\": \"CARBON\",\n"
            + "      \"opayCode\": \"100028\",\n"
            + "      \"shortCode\": \"565\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090530\",\n"
            + "      \"displayName\": \"CONFIDENCE MICROFINANCE BANK\",\n"
            + "      \"opayCode\": \"100029\",\n"
            + "      \"shortCode\": \"50197\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090365\",\n"
            + "      \"displayName\": \"CORESTEP MFB\",\n"
            + "      \"opayCode\": \"100030\",\n"
            + "      \"shortCode\": \"50204\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090429\",\n"
            + "      \"displayName\": \"CROSS RIVER MICROFINANCE LTD\",\n"
            + "      \"opayCode\": \"100031\",\n"
            + "      \"shortCode\": \"51305\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090445\",\n"
            + "      \"displayName\": \"Capstone Microfinance Bank\",\n"
            + "      \"opayCode\": \"100032\",\n"
            + "      \"shortCode\": \"50161\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090360\",\n"
            + "      \"displayName\": \"CashConnect Microfinance Bank\",\n"
            + "      \"opayCode\": \"100033\",\n"
            + "      \"shortCode\": \"865\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100005\",\n"
            + "      \"displayName\": \"Cellulant\",\n"
            + "      \"opayCode\": \"100034\",\n"
            + "      \"shortCode\": \"317\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090397\",\n"
            + "      \"displayName\": \"Chanelle Microfinance Bank\",\n"
            + "      \"opayCode\": \"100035\",\n"
            + "      \"shortCode\": \"50171\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090141\",\n"
            + "      \"displayName\": \"Chikum Microfinance Bank Ltd\",\n"
            + "      \"opayCode\": \"100036\",\n"
            + "      \"shortCode\": \"50177\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090553\",\n"
            + "      \"displayName\": \"Consistent Trust Micro Finance Bank\",\n"
            + "      \"opayCode\": \"100037\",\n"
            + "      \"shortCode\": \"50432\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"070006\",\n"
            + "      \"displayName\": \"Covenant Microfinance Bank\",\n"
            + "      \"opayCode\": \"100038\",\n"
            + "      \"shortCode\": \"50208\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000005\",\n"
            + "      \"displayName\": \"Diamond Bank\",\n"
            + "      \"opayCode\": \"100039\",\n"
            + "      \"shortCode\": \"063\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090470\",\n"
            + "      \"displayName\": \"Dot Microfinance Bank\",\n"
            + "      \"opayCode\": \"100040\",\n"
            + "      \"shortCode\": \"50162\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090294\",\n"
            + "      \"displayName\": \"Eagle Flight MFB\",\n"
            + "      \"opayCode\": \"100041\",\n"
            + "      \"shortCode\": \"50244\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100021\",\n"
            + "      \"displayName\": \"Eartholeum\",\n"
            + "      \"opayCode\": \"100042\",\n"
            + "      \"shortCode\": \"121\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100030\",\n"
            + "      \"displayName\": \"Ecobank Mobile\",\n"
            + "      \"opayCode\": \"100043\",\n"
            + "      \"shortCode\": \"307\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000010\",\n"
            + "      \"displayName\": \"Ecobank Nigeria Plc\",\n"
            + "      \"opayCode\": \"100044\",\n"
            + "      \"shortCode\": \"050\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100008\",\n"
            + "      \"displayName\": \"Ecobank Xpress Account\",\n"
            + "      \"opayCode\": \"100045\",\n"
            + "      \"shortCode\": \"108\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000019\",\n"
            + "      \"displayName\": \"Enterprise Bank\",\n"
            + "      \"opayCode\": \"100046\",\n"
            + "      \"shortCode\": \"084\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090541\",\n"
            + "      \"displayName\": \"Excellent Micro finance Bank\",\n"
            + "      \"opayCode\": \"100047\",\n"
            + "      \"shortCode\": \"50289\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090328\",\n"
            + "      \"displayName\": \"Eyowo\",\n"
            + "      \"opayCode\": \"100048\",\n"
            + "      \"shortCode\": \"328\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100031\",\n"
            + "      \"displayName\": \"FCMB Easy Account\",\n"
            + "      \"opayCode\": \"100049\",\n"
            + "      \"shortCode\": \"131\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000003\",\n"
            + "      \"displayName\": \"FCMB(First City Monument Bank PLC)\",\n"
            + "      \"opayCode\": \"100050\",\n"
            + "      \"shortCode\": \"214\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100001\",\n"
            + "      \"displayName\": \"FET\",\n"
            + "      \"opayCode\": \"100051\",\n"
            + "      \"shortCode\": \"314\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090153\",\n"
            + "      \"displayName\": \"FFS MFB\",\n"
            + "      \"opayCode\": \"100052\",\n"
            + "      \"shortCode\": \"944\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090400\",\n"
            + "      \"displayName\": \"FINCA MFB\",\n"
            + "      \"opayCode\": \"100053\",\n"
            + "      \"shortCode\": \"51128\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100014\",\n"
            + "      \"displayName\": \"FIRSTMONIE WALLET\",\n"
            + "      \"opayCode\": \"100054\",\n"
            + "      \"shortCode\": \"309\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"400001\",\n"
            + "      \"displayName\": \"FSDH Merchant Bank Limited\",\n"
            + "      \"opayCode\": \"100055\",\n"
            + "      \"shortCode\": \"501\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090551\",\n"
            + "      \"displayName\": \"Fairmoney MFB\",\n"
            + "      \"opayCode\": \"100056\",\n"
            + "      \"shortCode\": \"51318\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000007\",\n"
            + "      \"displayName\": \"Fidelity Bank\",\n"
            + "      \"opayCode\": \"100057\",\n"
            + "      \"shortCode\": \"070\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100019\",\n"
            + "      \"displayName\": \"Fidelity Mobile\",\n"
            + "      \"opayCode\": \"100058\",\n"
            + "      \"shortCode\": \"119\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090111\",\n"
            + "      \"displayName\": \"FinaTrust MFB\",\n"
            + "      \"opayCode\": \"100059\",\n"
            + "      \"shortCode\": \"608\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090366\",\n"
            + "      \"displayName\": \"Firmus Microfinance Bank\",\n"
            + "      \"opayCode\": \"100060\",\n"
            + "      \"shortCode\": \"51314\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000016\",\n"
            + "      \"displayName\": \"First Bank Of Nigeria\",\n"
            + "      \"opayCode\": \"100061\",\n"
            + "      \"shortCode\": \"011\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090614\",\n"
            + "      \"displayName\": \"Flourish MFB\",\n"
            + "      \"opayCode\": \"100062\",\n"
            + "      \"shortCode\": \"50315\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"110002\",\n"
            + "      \"displayName\": \"Flutterwave Technology Solutions Limited\",\n"
            + "      \"opayCode\": \"100063\",\n"
            + "      \"shortCode\": \"211\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100016\",\n"
            + "      \"displayName\": \"FortisMobile\",\n"
            + "      \"opayCode\": \"100064\",\n"
            + "      \"shortCode\": \"116\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090486\",\n"
            + "      \"displayName\": \"Fortress Microfinance Bank\",\n"
            + "      \"opayCode\": \"100065\",\n"
            + "      \"shortCode\": \"50318\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100009\",\n"
            + "      \"displayName\": \"GTMobile\",\n"
            + "      \"opayCode\": \"100066\",\n"
            + "      \"shortCode\": \"109\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090591\",\n"
            + "      \"displayName\": \"Gabsyn Microfinance Bank Limited\",\n"
            + "      \"opayCode\": \"100067\",\n"
            + "      \"shortCode\": \"51342\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"070009\",\n"
            + "      \"displayName\": \"Gateway Mortgage Bank\",\n"
            + "      \"opayCode\": \"100068\",\n"
            + "      \"shortCode\": \"812\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000027\",\n"
            + "      \"displayName\": \"Globus Bank\",\n"
            + "      \"opayCode\": \"100069\",\n"
            + "      \"shortCode\": \"103\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090278\",\n"
            + "      \"displayName\": \"Glory Microfinance Bank\",\n"
            + "      \"opayCode\": \"100070\",\n"
            + "      \"shortCode\": \"50350\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100022\",\n"
            + "      \"displayName\": \"GoMoney\",\n"
            + "      \"opayCode\": \"100071\",\n"
            + "      \"shortCode\": \"450\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090586\",\n"
            + "      \"displayName\": \"Gombe Microfinance Bank Limited\",\n"
            + "      \"opayCode\": \"100072\",\n"
            + "      \"shortCode\": \"50357\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090495\",\n"
            + "      \"displayName\": \"Good News Microfinance Bank\",\n"
            + "      \"opayCode\": \"100073\",\n"
            + "      \"shortCode\": \"50739\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000013\",\n"
            + "      \"displayName\": \"Guaranty Trust Bank\",\n"
            + "      \"opayCode\": \"100074\",\n"
            + "      \"shortCode\": \"058\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100017\",\n"
            + "      \"displayName\": \"Hedonmark\",\n"
            + "      \"opayCode\": \"100075\",\n"
            + "      \"shortCode\": \"117\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000020\",\n"
            + "      \"displayName\": \"Heritage Banking\",\n"
            + "      \"opayCode\": \"100076\",\n"
            + "      \"shortCode\": \"030\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"120002\",\n"
            + "      \"displayName\": \"Hope PSB\",\n"
            + "      \"opayCode\": \"100077\",\n"
            + "      \"shortCode\": \"800\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090430\",\n"
            + "      \"displayName\": \"ILORA Microfinance Bank\",\n"
            + "      \"opayCode\": \"100078\",\n"
            + "      \"shortCode\": \"50447\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090118\",\n"
            + "      \"displayName\": \"Ibile Microfinance Bank Limited\",\n"
            + "      \"opayCode\": \"100079\",\n"
            + "      \"shortCode\": \"51244\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090532\",\n"
            + "      \"displayName\": \"Ibolo MFB\",\n"
            + "      \"opayCode\": \"100080\",\n"
            + "      \"shortCode\": \"50402\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090519\",\n"
            + "      \"displayName\": \"Ibom Fadama MFB Ltd\",\n"
            + "      \"opayCode\": \"100081\",\n"
            + "      \"shortCode\": \"51321\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090279\",\n"
            + "      \"displayName\": \"Ikire Microfinance Bank\",\n"
            + "      \"opayCode\": \"100082\",\n"
            + "      \"shortCode\": \"50435\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100029\",\n"
            + "      \"displayName\": \"Innovectives Kesh\",\n"
            + "      \"opayCode\": \"100083\",\n"
            + "      \"shortCode\": \"129\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090434\",\n"
            + "      \"displayName\": \"Insight Microfinance Bank\",\n"
            + "      \"opayCode\": \"100084\",\n"
            + "      \"shortCode\": \"50460\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100027\",\n"
            + "      \"displayName\": \"Intellifin\",\n"
            + "      \"opayCode\": \"100085\",\n"
            + "      \"shortCode\": \"127\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090570\",\n"
            + "      \"displayName\": \"Iyamoye Microfinance Bank\",\n"
            + "      \"opayCode\": \"100086\",\n"
            + "      \"shortCode\": \"5048850925\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090620\",\n"
            + "      \"displayName\": \"Iyin Ekiti Microfinance Bank\",\n"
            + "      \"opayCode\": \"100087\",\n"
            + "      \"shortCode\": \"50491\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000006\",\n"
            + "      \"displayName\": \"Jaiz Bank Plc\",\n"
            + "      \"opayCode\": \"100088\",\n"
            + "      \"shortCode\": \"301\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090003\",\n"
            + "      \"displayName\": \"Jubilee Life Mortgage\",\n"
            + "      \"opayCode\": \"100089\",\n"
            + "      \"shortCode\": \"402\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090549\",\n"
            + "      \"displayName\": \"KC Microfinance Bank\",\n"
            + "      \"opayCode\": \"100090\",\n"
            + "      \"shortCode\": \"50529\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100015\",\n"
            + "      \"displayName\": \"Kegow\",\n"
            + "      \"opayCode\": \"100091\",\n"
            + "      \"shortCode\": \"115\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100036\",\n"
            + "      \"displayName\": \"Kegow (Chamsmobile)\",\n"
            + "      \"opayCode\": \"100092\",\n"
            + "      \"shortCode\": \"00719\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000002\",\n"
            + "      \"displayName\": \"Keystone Bank\",\n"
            + "      \"opayCode\": \"100093\",\n"
            + "      \"shortCode\": \"082\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100025\",\n"
            + "      \"displayName\": \"KongaPay Technologies Limited\",\n"
            + "      \"opayCode\": \"100094\",\n"
            + "      \"shortCode\": \"125\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090380\",\n"
            + "      \"displayName\": \"Kredi Money Microfinance Bank\",\n"
            + "      \"opayCode\": \"100095\",\n"
            + "      \"shortCode\": \"50200\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090267\",\n"
            + "      \"displayName\": \"Kuda MFB\",\n"
            + "      \"opayCode\": \"100096\",\n"
            + "      \"shortCode\": \"423\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090177\",\n"
            + "      \"displayName\": \"Lapo Microfinance Bank\",\n"
            + "      \"opayCode\": \"100097\",\n"
            + "      \"shortCode\": \"50547\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090271\",\n"
            + "      \"displayName\": \"Lavender Microfinance Bank \",\n"
            + "      \"opayCode\": \"100098\",\n"
            + "      \"shortCode\": \"50538\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090650\",\n"
            + "      \"displayName\": \"Leadcity Microfinance Bank\",\n"
            + "      \"opayCode\": \"100099\",\n"
            + "      \"shortCode\": \"50541\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090420\",\n"
            + "      \"displayName\": \"Letshego Microfinance Bank\",\n"
            + "      \"opayCode\": \"100100\",\n"
            + "      \"shortCode\": \"920\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090557\",\n"
            + "      \"displayName\": \"LifeGate MFB\",\n"
            + "      \"opayCode\": \"100101\",\n"
            + "      \"shortCode\": \"50546\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090435\",\n"
            + "      \"displayName\": \"Links Microfinance Bank\",\n"
            + "      \"opayCode\": \"100102\",\n"
            + "      \"shortCode\": \"50549\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"070007\",\n"
            + "      \"displayName\": \"LivingTrust Mortgage Bank PLC\",\n"
            + "      \"opayCode\": \"100103\",\n"
            + "      \"shortCode\": \"031\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000029\",\n"
            + "      \"displayName\": \"Lotus Bank\",\n"
            + "      \"opayCode\": \"100104\",\n"
            + "      \"shortCode\": \"303\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090281\",\n"
            + "      \"displayName\": \"MINT - FINEX MFB\",\n"
            + "      \"opayCode\": \"100105\",\n"
            + "      \"shortCode\": \"50304\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090405\",\n"
            + "      \"displayName\": \"MONIE POINT\",\n"
            + "      \"opayCode\": \"100106\",\n"
            + "      \"shortCode\": \"50515\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090323\",\n"
            + "      \"displayName\": \"Mainland Microfinance Bank\",\n"
            + "      \"opayCode\": \"100107\",\n"
            + "      \"shortCode\": \"50557\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090383\",\n"
            + "      \"displayName\": \"Manny Microfinance bank\",\n"
            + "      \"opayCode\": \"100108\",\n"
            + "      \"shortCode\": \"51313\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090589\",\n"
            + "      \"displayName\": \"Mercury Microfinance Bank\",\n"
            + "      \"opayCode\": \"100109\",\n"
            + "      \"shortCode\": \"50571\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090113\",\n"
            + "      \"displayName\": \"Microvis Microfinance Bank\",\n"
            + "      \"opayCode\": \"100110\",\n"
            + "      \"shortCode\": \"51209\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100011\",\n"
            + "      \"displayName\": \"Mkudi\",\n"
            + "      \"opayCode\": \"100111\",\n"
            + "      \"shortCode\": \"111\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"120003\",\n"
            + "      \"displayName\": \"Momo Payment Service Bank\",\n"
            + "      \"opayCode\": \"100112\",\n"
            + "      \"shortCode\": \"948\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090462\",\n"
            + "      \"displayName\": \"Monarch Microfinance Bank\",\n"
            + "      \"opayCode\": \"100113\",\n"
            + "      \"shortCode\": \"50948\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100020\",\n"
            + "      \"displayName\": \"MoneyBox\",\n"
            + "      \"opayCode\": \"100114\",\n"
            + "      \"shortCode\": \"120\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"120005\",\n"
            + "      \"displayName\": \"MoneyMaster PSB\",\n"
            + "      \"opayCode\": \"100115\",\n"
            + "      \"shortCode\": \"946\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090329\",\n"
            + "      \"displayName\": \"Neptune Microfinance Bank Ltd\",\n"
            + "      \"opayCode\": \"100116\",\n"
            + "      \"shortCode\": \"51306\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090205\",\n"
            + "      \"displayName\": \"New Dawn Microfinance bank\",\n"
            + "      \"opayCode\": \"100117\",\n"
            + "      \"shortCode\": \"51291\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000009\",\n"
            + "      \"displayName\": \"Nigeria Int'l Bank (CITIGROUP)\",\n"
            + "      \"opayCode\": \"100118\",\n"
            + "      \"shortCode\": \"023\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100032\",\n"
            + "      \"displayName\": \"NowNow\",\n"
            + "      \"opayCode\": \"100119\",\n"
            + "      \"shortCode\": \"132\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100004\",\n"
            + "      \"displayName\": \"OPay\",\n"
            + "      \"opayCode\": \"100120\",\n"
            + "      \"shortCode\": \"305\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090654\",\n"
            + "      \"displayName\": \"Odoakpu Microfinance Bank Limited\",\n"
            + "      \"opayCode\": \"100121\",\n"
            + "      \"shortCode\": \"50653\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090646\",\n"
            + "      \"displayName\": \"Okengwe Microfinance Bank\",\n"
            + "      \"opayCode\": \"100122\",\n"
            + "      \"shortCode\": \"50676\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090566\",\n"
            + "      \"displayName\": \"Okuku Microfinance Bank\",\n"
            + "      \"opayCode\": \"100123\",\n"
            + "      \"shortCode\": \"50684\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000036\",\n"
            + "      \"displayName\": \"Optimus Bank\",\n"
            + "      \"opayCode\": \"100124\",\n"
            + "      \"shortCode\": \"00107\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090588\",\n"
            + "      \"displayName\": \"Orisun Microfinance Bank\",\n"
            + "      \"opayCode\": \"100125\",\n"
            + "      \"shortCode\": \"50715\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100002\",\n"
            + "      \"displayName\": \"Paga\",\n"
            + "      \"opayCode\": \"100126\",\n"
            + "      \"shortCode\": \"327\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100033\",\n"
            + "      \"displayName\": \"Palmpay\",\n"
            + "      \"opayCode\": \"100127\",\n"
            + "      \"shortCode\": \"312\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000030\",\n"
            + "      \"displayName\": \"Parallex Bank\",\n"
            + "      \"opayCode\": \"100128\",\n"
            + "      \"shortCode\": \"949\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100003\",\n"
            + "      \"displayName\": \"Parkway Bank\",\n"
            + "      \"opayCode\": \"100129\",\n"
            + "      \"shortCode\": \"311\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090317\",\n"
            + "      \"displayName\": \"PatrickGold MicroFinance Bank\",\n"
            + "      \"opayCode\": \"100130\",\n"
            + "      \"shortCode\": \"50956\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090402\",\n"
            + "      \"displayName\": \"Peace Microfinance Bank\",\n"
            + "      \"opayCode\": \"100131\",\n"
            + "      \"shortCode\": \"50743\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090289\",\n"
            + "      \"displayName\": \"Pillar Microfinance Bank\",\n"
            + "      \"opayCode\": \"100132\",\n"
            + "      \"shortCode\": \"50983\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000008\",\n"
            + "      \"displayName\": \"Polaris Bank Plc\",\n"
            + "      \"opayCode\": \"100133\",\n"
            + "      \"shortCode\": \"076\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090412\",\n"
            + "      \"displayName\": \"Preeminent Microfinance Bank\",\n"
            + "      \"opayCode\": \"100134\",\n"
            + "      \"shortCode\": \"51309\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000031\",\n"
            + "      \"displayName\": \"Premium Trust Bank\",\n"
            + "      \"opayCode\": \"100135\",\n"
            + "      \"shortCode\": \"105\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000023\",\n"
            + "      \"displayName\": \"Providus Bank Plc\",\n"
            + "      \"opayCode\": \"100136\",\n"
            + "      \"shortCode\": \"101\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090303\",\n"
            + "      \"displayName\": \"Purplemoney Microfinance Bank\",\n"
            + "      \"opayCode\": \"100137\",\n"
            + "      \"shortCode\": \"51196\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090657\",\n"
            + "      \"displayName\": \"Pyramid Microfinance Bank\",\n"
            + "      \"opayCode\": \"100138\",\n"
            + "      \"shortCode\": \"50757\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000024\",\n"
            + "      \"displayName\": \"Rand Merchant Bank\",\n"
            + "      \"opayCode\": \"100139\",\n"
            + "      \"shortCode\": \"502\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090463\",\n"
            + "      \"displayName\": \"Rehoboth Microfinance Bank\",\n"
            + "      \"opayCode\": \"100140\",\n"
            + "      \"shortCode\": \"50761\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090198\",\n"
            + "      \"displayName\": \"Renmoney\",\n"
            + "      \"opayCode\": \"100141\",\n"
            + "      \"shortCode\": \"51049\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090433\",\n"
            + "      \"displayName\": \"Rigo Microfinance Bank Limited\",\n"
            + "      \"opayCode\": \"100142\",\n"
            + "      \"shortCode\": \"51286\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090622\",\n"
            + "      \"displayName\": \"Royal Blue Microfinance Bank\",\n"
            + "      \"opayCode\": \"100143\",\n"
            + "      \"shortCode\": \"50768\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090175\",\n"
            + "      \"displayName\": \"Rubies MFB\",\n"
            + "      \"opayCode\": \"100144\",\n"
            + "      \"shortCode\": \"587\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090449\",\n"
            + "      \"displayName\": \"SLS Microfinance Bank\",\n"
            + "      \"opayCode\": \"100145\",\n"
            + "      \"shortCode\": \"51108\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090506\",\n"
            + "      \"displayName\": \"SOLID ALLIANZE MFB\",\n"
            + "      \"opayCode\": \"100146\",\n"
            + "      \"shortCode\": \"51062\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090436\",\n"
            + "      \"displayName\": \"SPECTRUM MICROFINANCE BANK\",\n"
            + "      \"opayCode\": \"100147\",\n"
            + "      \"shortCode\": \"50756\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090286\",\n"
            + "      \"displayName\": \"Safe Haven Microfinance Bank\",\n"
            + "      \"opayCode\": \"100148\",\n"
            + "      \"shortCode\": \"51113\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000034\",\n"
            + "      \"displayName\": \"Signature bank\",\n"
            + "      \"opayCode\": \"100149\",\n"
            + "      \"shortCode\": \"061\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"120004\",\n"
            + "      \"displayName\": \"SmartCash Payment Service Bank\",\n"
            + "      \"opayCode\": \"100150\",\n"
            + "      \"shortCode\": \"00803\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090325\",\n"
            + "      \"displayName\": \"Sparkle\",\n"
            + "      \"opayCode\": \"100151\",\n"
            + "      \"shortCode\": \"51310\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100007\",\n"
            + "      \"displayName\": \"Stanbic IBTC @ease Wallet\",\n"
            + "      \"opayCode\": \"100152\",\n"
            + "      \"shortCode\": \"107\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000012\",\n"
            + "      \"displayName\": \"Stanbic-ibtc Bank Plc\",\n"
            + "      \"opayCode\": \"100153\",\n"
            + "      \"shortCode\": \"221\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000021\",\n"
            + "      \"displayName\": \"Standard Chartered Bank\",\n"
            + "      \"opayCode\": \"100154\",\n"
            + "      \"shortCode\": \"068\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090262\",\n"
            + "      \"displayName\": \"Stella MFB\",\n"
            + "      \"opayCode\": \"100155\",\n"
            + "      \"shortCode\": \"51253\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000001\",\n"
            + "      \"displayName\": \"Sterling Bank\",\n"
            + "      \"opayCode\": \"100156\",\n"
            + "      \"shortCode\": \"232\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090305\",\n"
            + "      \"displayName\": \"Sulspap Microfinance Bank\",\n"
            + "      \"opayCode\": \"100157\",\n"
            + "      \"shortCode\": \"51199\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000022\",\n"
            + "      \"displayName\": \"Suntrust Bank\",\n"
            + "      \"opayCode\": \"100158\",\n"
            + "      \"shortCode\": \"100\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090446\",\n"
            + "      \"displayName\": \"Support Microfinance Bank Limited\",\n"
            + "      \"opayCode\": \"100159\",\n"
            + "      \"shortCode\": \"50812\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000026\",\n"
            + "      \"displayName\": \"TAJBank\",\n"
            + "      \"opayCode\": \"100160\",\n"
            + "      \"shortCode\": \"302\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"080002\",\n"
            + "      \"displayName\": \"TAJ_PINSPAY\",\n"
            + "      \"opayCode\": \"100161\",\n"
            + "      \"shortCode\": \"00302\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090560\",\n"
            + "      \"displayName\": \"TANADI MFB (CRUST)\",\n"
            + "      \"opayCode\": \"100162\",\n"
            + "      \"shortCode\": \"51036\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090283\",\n"
            + "      \"displayName\": \"THRIVE MFB\",\n"
            + "      \"opayCode\": \"100163\",\n"
            + "      \"shortCode\": \"51183\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100023\",\n"
            + "      \"displayName\": \"TagPay\",\n"
            + "      \"opayCode\": \"100164\",\n"
            + "      \"shortCode\": \"123\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100010\",\n"
            + "      \"displayName\": \"TeasyMobile\",\n"
            + "      \"opayCode\": \"100165\",\n"
            + "      \"shortCode\": \"110\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090373\",\n"
            + "      \"displayName\": \"Think MFB\",\n"
            + "      \"opayCode\": \"100166\",\n"
            + "      \"shortCode\": \"51262\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000025\",\n"
            + "      \"displayName\": \"Titan Trust Bank\",\n"
            + "      \"opayCode\": \"100167\",\n"
            + "      \"shortCode\": \"102\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100039\",\n"
            + "      \"displayName\": \"Titan-Paystack\",\n"
            + "      \"opayCode\": \"100168\",\n"
            + "      \"shortCode\": \"10105\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090613\",\n"
            + "      \"displayName\": \"Total Trust Microfinance Bank\",\n"
            + "      \"opayCode\": \"100169\",\n"
            + "      \"shortCode\": \"50825\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090652\",\n"
            + "      \"displayName\": \"Umuchukwu Microfinance Bank\",\n"
            + "      \"opayCode\": \"100170\",\n"
            + "      \"shortCode\": \"50863\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000018\",\n"
            + "      \"displayName\": \"Union Bank Of Nigeria\",\n"
            + "      \"opayCode\": \"100171\",\n"
            + "      \"shortCode\": \"032\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000004\",\n"
            + "      \"displayName\": \"United Bank For Africa\",\n"
            + "      \"opayCode\": \"100172\",\n"
            + "      \"shortCode\": \"033\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000011\",\n"
            + "      \"displayName\": \"Unity Bank Plc\",\n"
            + "      \"opayCode\": \"100173\",\n"
            + "      \"shortCode\": \"215\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090110\",\n"
            + "      \"displayName\": \"VFD MFB\",\n"
            + "      \"opayCode\": \"100174\",\n"
            + "      \"shortCode\": \"566\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100012\",\n"
            + "      \"displayName\": \"VTNetworks\",\n"
            + "      \"opayCode\": \"100175\",\n"
            + "      \"shortCode\": \"112\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090590\",\n"
            + "      \"displayName\": \"WAYA MICROFINANCE BANK\",\n"
            + "      \"opayCode\": \"100176\",\n"
            + "      \"shortCode\": \"51355\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000017\",\n"
            + "      \"displayName\": \"Wema Bank PLC\",\n"
            + "      \"opayCode\": \"100177\",\n"
            + "      \"shortCode\": \"035\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090120\",\n"
            + "      \"displayName\": \"Wetland MFB\",\n"
            + "      \"opayCode\": \"100178\",\n"
            + "      \"shortCode\": \"871\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090142\",\n"
            + "      \"displayName\": \"Yes Microfinance Bank\",\n"
            + "      \"opayCode\": \"100179\",\n"
            + "      \"shortCode\": \"51234\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"000015\",\n"
            + "      \"displayName\": \"Zenith Bank\",\n"
            + "      \"opayCode\": \"100180\",\n"
            + "      \"shortCode\": \"057\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100018\",\n"
            + "      \"displayName\": \"Zenith Mobile\",\n"
            + "      \"opayCode\": \"100181\",\n"
            + "      \"shortCode\": \"322\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"090504\",\n"
            + "      \"displayName\": \"Zikora Microfinance bank\",\n"
            + "      \"opayCode\": \"100182\",\n"
            + "      \"shortCode\": \"51329\"\n"
            + "    },\n"
            + "    {\n"
            + "      \"altCode\": \"100006\",\n"
            + "      \"displayName\": \"eTranzact\",\n"
            + "      \"opayCode\": \"100183\",\n"
            + "      \"shortCode\": \"106\"\n"
            + "    }\n"
            + "  ]\n"
            + "}";
;
    JsonData jsonData = JSON.parseObject(dataJson, JsonData.class);
    // jsonData.getData().forEach(System.out::println);
    List<DataDTO> banks =
        jsonData.getData().stream()
            .sorted((b1, b2) -> b1.getDisplayName().compareTo(b2.getDisplayName()))
            .collect(Collectors.toList());
//    int start = 100000;
//    for (DataDTO dataDTO : banks) {
//      dataDTO.setOpayCode(start + "");
//      start++;
//    }
    System.out.println(JSON.toJSONString(banks));
  }
}
